artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion/
  data_path : datasets/LibriSpeech/
  audio_path : artifacts/data_ingestion/audio/
  source_URL : https://www.openslr.org/resources/12/train-clean-100.tar.gz
  local_data_file: artifacts/data_ingestion/

data_transformation:
  root_dir: artifacts/data_transformation/
  data_path: artifacts/data_ingestion/
  audio_path : artifacts/data_ingestion/audio/
  preprocessor_object_file: artifacts/data_transformation/preprocessor.pkl
  train_data_path: artifacts/data_ingestion/train.csv
  test_data_path: artifacts/data_ingestion/test.csv
  processed_train_path: artifacts/data_transformation/train_processed.csv
  processed_test_path: artifacts/data_transformation/test_processed.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_ingestion/train.csv
  test_data_path: artifacts/data_ingestion/test.csv
  model_name: model.pt
  target_column: transcript
